spring.application.name=walley

# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5432/walley_dev
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Thymeleaf
spring.thymeleaf.cache=false


logging.level.org.springframework.web=INFO
logging.level.org.fin.walley=DEBUG


server.port=8080